In [1]:
import pandas as pd
import numpy as np
import re
import nltk
nltk.download('stopwords')
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/anfang/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
dataset = pd.read_csv('dataset.csv', index_col = 'Unnamed: 0')
print(dataset.shape)

(24783, 6)


In [3]:
dataset.index=[np.arange(24783)]

In [4]:
dataset.head()

count  hate_speech  offensive_language  neither  class  \
0      3            0                   0        3      2   
1      3            0                   3        0      1   
2      3            0                   3        0      1   
3      3            0                   2        1      1   
4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [5]:
y=dataset['class'].values
y

array([2, 1, 1, ..., 1, 1, 2])

## Preprocess

In [10]:
corpus=[]
for i in range(0,24783):
#     review = dataset['tweet'][i]
#     review = review.split()
#     review = [word for word in review if "@" not in word] # replace id_name
#     review=' '.join(review)
#     review = re.sub('[^a-zA-Z]',' ',review)
    
    review = re.sub('[^a-zA-Z]',' ',dataset['tweet'][i]) #replace non-character with space
    review=review.lower()  #lowercasing
    review=review.split()
    ps=PorterStemmer()     #stemming
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)

## Embedding

In [11]:
from sklearn.feature_extraction.text import CountVectorizer    
cv=CountVectorizer(max_features=3600)
x=cv.fit_transform(corpus).toarray()

## Train and Text Split

In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.15, random_state=0)

## Classifiers

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix

### Decision Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train,y_train)
pred=classifier.predict(X_test)

In [14]:
cm=confusion_matrix(y_test,pred)
print("confusion matrix")
print(cm)
print('Accuracy score: {}'.format(accuracy_score(y_test, pred)))
print('Precision score: {}'.format(precision_score(y_test, pred,average='weighted')))
print('Recall score: {}'.format(recall_score(y_test, pred,average='weighted')))

confusion matrix
[[  75  115   15]
 [ 144 2657   80]
 [  29   79  524]]
Accuracy score: 0.8757396449704142
Precision score: 0.8827217389140051
Recall score: 0.8757396449704142


### Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [16]:
print("confusion matrix")
print(cm)
print('Accuracy is {} '.format(accuracy_score(y_test, y_pred)))
print('Precision is {} '.format(precision_score(y_test, y_pred,average='weighted')))
print('Recall is {} '.format(recall_score(y_test, y_pred,average='weighted')))

confusion matrix
[[  75  115   15]
 [ 144 2657   80]
 [  29   79  524]]
Accuracy is 0.9031737493275955 
Precision is 0.8916640693985272 
Recall is 0.9031737493275955 


### SVM

In [ ]:
from sklearn.svm import SVC # "Support vector classifier"
classifier = SVC(kernel='linear', C=1E10) # We choose C, which is a regularization parameter, very large. More details below
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

In [ ]:
print("confusion matrix")
print(cm)
print('Accuracy is {} '.format(accuracy_score(y_test, y_pred)))
print('Precision is {} '.format(precision_score(y_test, y_pred,average='weighted')))
print('Recall is {} '.format(recall_score(y_test, y_pred,average='weighted')))